import type { Metadata } from "next";
import { Inter, DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import { Theme } from '@radix-ui/themes';

// Configure both Inter and DM Sans fonts
const inter = Inter({ subsets: ["latin"] });
const dmSans = DM_Sans({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style
          id="font-dm-sans"
          dangerouslySetInnerHTML={{
            __html: `:root { --font-dm-sans: ${dmSans.style.fontFamily}; }`,
          }}
        />
      </head>
      <body className={`${inter.className} font-sans`} >
        <Theme>
        <Navbar />
        {children}

        </Theme>
      </body>
    </html>
  );
}
